### ISSUE TITLE
generators need update

### ISSUE THREAD

**Issue by r0zar** [marcinwyszynski/cabalist#3]
Depreciation warnings issued about the use of `match` in `routes.rb`.

Also, seeing: `/.rvm/gems/ruby-2.2.1/gems/cabalist-0.0.4/lib/generators/cabalist/classifier/classifier_generator.rb:27:in`create_migration': wrong number of arguments (3 for 0) (ArgumentError)`

**Comment by marcinwyszynski** [comment]
Truth is that this whole gem badly needs some love. Ruby 2.0 wasn't even out yet when it was released and it hasn't really been updated since. I'll get to it one day.

**Comment by Heshuge** [comment]
Ahhh! I'm sorry!
I really like the way you used generators to add a "predicted" data field to models.
If I ever get a chance to implement something like that, I'll be sure to remember where I got the idea! ^_^
Thanks.
